# 🧹 Section 1: Data Cleaning

In [57]:
import pandas as pd
import numpy as np
df = pd.read_csv('health_and_wellness_cleaned_20230810_213000.csv')
pd.options.display.float_format = '{:,.2f}'.format

In [58]:
df.drop_duplicates(inplace=True)

In [59]:
df

,Id,Section,Name,Price,Total Sold,Total Reviews,Shop Location
0,4799179886,Acne Care,DHC Vitamin B-Mix วิตามินบีรวม (สำหรับ 20 วัน),฿75.00,NaN,NaN,Pathum Thani
1,4795171651,Acne Care,ซิงค์ Vistra Zinc วิสทร้า ซิงค์ 15 มก. ขนาด 20...,฿79.00,NaN,NaN,Chiang Mai
2,4790242641,Acne Care,Blackmores แบลคมอร์ส Bio Zinc A Chelate (90 T...,฿224.00,NaN,NaN,Surin
3,4789940606,Acne Care,1แถม1 กลูต้าวิตมี กลูต้าส้มเลือด Gluta With Me...,฿290.00,NaN,NaN,Udon Thani
4,4787161067,Acne Care,🎌 DHC Vitamin B-Mix Persistent วิตามินบีรวม แบ...,฿149.00,NaN,NaN,Bangkok
...,...,...,...,...,...,...,...
67517,4806492324,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,฿220.00,50 ชิ้น,NaN,Bangkok
67518,4806483337,Food Supplement,โคลีนบี วิตามินบีรวม วิตามินบี Choline - B G...,฿280.00,69 ชิ้น,NaN,Bangkok
67532,4808549166,Food Supplement,Goodies โปรตีนพืชรสช็อคโกแลต 1 กระปุก,"฿1,390.00",NaN,(3),Nakhon Pathom
67553,4808500844,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,฿560.00,48 ชิ้น,NaN,Pathum Thani
67557,4806492324,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,฿560.00,50 ชิ้น,NaN,Bangkok

In [60]:
df.dtypes

Id                int64
Section          object
Name             object
Price            object
Total Sold       object
Total Reviews    object
Shop Location    object
dtype: object

In [61]:
df['Price']

0           ฿75.00
1           ฿79.00
2          ฿224.00
3          ฿290.00
4          ฿149.00
           ...
67517      ฿220.00
67518      ฿280.00
67532    ฿1,390.00
67553      ฿560.00
67557      ฿560.00
Name: Price, Length: 2622, dtype: object

In [62]:
df['Price'] = df['Price'].str.replace('[^\d.]','',regex=True).astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\vinny\AppData\Local\Temp\ipykernel_17136\638380408.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Price'] = df['Price'].str.replace('[^\d.]','',regex=True).astype(float)

In [63]:
df.isnull().sum()

Id                  0
Section             0
Name                0
Price               0
Total Sold       1202
Total Reviews    1061
Shop Location       5
dtype: int64

In [64]:
df

,Id,Section,Name,Price,Total Sold,Total Reviews,Shop Location
0,4799179886,Acne Care,DHC Vitamin B-Mix วิตามินบีรวม (สำหรับ 20 วัน),75.00,NaN,NaN,Pathum Thani
1,4795171651,Acne Care,ซิงค์ Vistra Zinc วิสทร้า ซิงค์ 15 มก. ขนาด 20...,79.00,NaN,NaN,Chiang Mai
2,4790242641,Acne Care,Blackmores แบลคมอร์ส Bio Zinc A Chelate (90 T...,224.00,NaN,NaN,Surin
3,4789940606,Acne Care,1แถม1 กลูต้าวิตมี กลูต้าส้มเลือด Gluta With Me...,290.00,NaN,NaN,Udon Thani
4,4787161067,Acne Care,🎌 DHC Vitamin B-Mix Persistent วิตามินบีรวม แบ...,149.00,NaN,NaN,Bangkok
...,...,...,...,...,...,...,...
67517,4806492324,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,220.00,50 ชิ้น,NaN,Bangkok
67518,4806483337,Food Supplement,โคลีนบี วิตามินบีรวม วิตามินบี Choline - B G...,280.00,69 ชิ้น,NaN,Bangkok
67532,4808549166,Food Supplement,Goodies โปรตีนพืชรสช็อคโกแลต 1 กระปุก,"1,390.00",NaN,(3),Nakhon Pathom
67553,4808500844,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,560.00,48 ชิ้น,NaN,Pathum Thani
67557,4806492324,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,560.00,50 ชิ้น,NaN,Bangkok

In [65]:
df['Shop Location'].value_counts()

Shop Location
Bangkok         1101
Pathum Thani     237
Nonthaburi       197
Samut Prakan     167
Chiang Mai        89
                ...
Ang Thong          1
Nan                1
Krabi              1
Satun              1
ต่างประเทศ         1
Name: count, Length: 71, dtype: int64

In [66]:
df[df['Shop Location'].isnull()][['Name','Price','Total Sold','Total Reviews']]

,Name,Price,Total Sold,Total Reviews
47051,ว่านร้อยชัยของแท้ ว่านร้อยชาย-วิตามินเสริมเสน่...,90.00,"1,930 ชิ้น",(244)
58653,มายาอาร์เอ็ม สูตรเดิม เพ็คเกจใหม่ล่าสุด,80.00,NaN,NaN
58693,มายาอาร์เอ็ม สูตรเดิม เพ็คเกจใหม่ล่าสุด,220.00,NaN,NaN
64160,วิตามินเพิ่มน้ำหนักคลีนิค เวย์โปรตีนเพิ่มน้ำหน...,65.00,134 ชิ้น,(14)
64225,วิตามินเพิ่มน้ำหนักคุณนาย 15 วัน เวย์โปรตีนเพิ...,89.00,8 ชิ้น,NaN

In [67]:
condition = (df['Total Sold'] == 0) & (df['Total Reviews'] == 0) & (df['Shop Location'].isnull())
df = df[~condition].copy()

In [68]:
df['Shop Location'] = df['Shop Location'].fillna("Unknown")

In [69]:
df['Total Sold'] = df['Total Sold'].str.replace(r'[^\d]', '', regex=True)
df['Total Reviews'] = df['Total Reviews'].str.replace(r'[^\d]', '', regex=True)

In [70]:
df['Total Sold'] = df['Total Sold'].replace('', None).fillna(0).astype(int)
df['Total Reviews'] = df['Total Reviews'].replace('',None).fillna(0).astype(int)

In [71]:
df

,Id,Section,Name,Price,Total Sold,Total Reviews,Shop Location
0,4799179886,Acne Care,DHC Vitamin B-Mix วิตามินบีรวม (สำหรับ 20 วัน),75.00,0,0,Pathum Thani
1,4795171651,Acne Care,ซิงค์ Vistra Zinc วิสทร้า ซิงค์ 15 มก. ขนาด 20...,79.00,0,0,Chiang Mai
2,4790242641,Acne Care,Blackmores แบลคมอร์ส Bio Zinc A Chelate (90 T...,224.00,0,0,Surin
3,4789940606,Acne Care,1แถม1 กลูต้าวิตมี กลูต้าส้มเลือด Gluta With Me...,290.00,0,0,Udon Thani
4,4787161067,Acne Care,🎌 DHC Vitamin B-Mix Persistent วิตามินบีรวม แบ...,149.00,0,0,Bangkok
...,...,...,...,...,...,...,...
67517,4806492324,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,220.00,50,0,Bangkok
67518,4806483337,Food Supplement,โคลีนบี วิตามินบีรวม วิตามินบี Choline - B G...,280.00,69,0,Bangkok
67532,4808549166,Food Supplement,Goodies โปรตีนพืชรสช็อคโกแลต 1 กระปุก,"1,390.00",0,3,Nakhon Pathom
67553,4808500844,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,560.00,48,0,Pathum Thani
67557,4806492324,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,560.00,50,0,Bangkok

_____________________________________________________________________________________________________

# 📊 Section 2: EDA & Analysis

In [72]:
df['Section'].value_counts()

Section
Skin Nourishment                 137
Pregnancy Care                   128
Detoxification                   112
Pre-Workout                      100
Fat Blockers & Burners            98
Bone & Joint Support              94
Well Being Gifts & Value Sets     93
Digestive Care                    92
Protein                           89
Beauty Supplements Value Sets     87
Sexual Health Vitamins            85
Appetite Suppressant              85
Immunity                          85
Whitening                         84
Heart & Blood Pressure            82
Women's Health                    82
Nutritional Foods & Drinks        82
Slimming Beverages                82
Multivitamins                     82
Herbs & Traditional Medicine      82
Acne Care                         82
Stress, Sleep, and Anxiety        82
Mass Gainer                       82
Weight Management Value Sets      82
Men's Health                      81
Brain & Memory                    81
Breast Enlargement                80
Meal Replacement                  80
Hair & Nail                       79
Food Supplement                   32
Name: count, dtype: int64

In [73]:
df.groupby('Section')['Price'].agg(['count','mean','median']).sort_values('count',ascending=False)

                               count   mean  median
Section
Skin Nourishment                 137 301.17  200.00
Pregnancy Care                   128 662.84  540.00
Detoxification                   112 501.95  332.50
Pre-Workout                      100 716.75  560.00
Fat Blockers & Burners            98 516.55  179.00
Bone & Joint Support              94 591.33  387.00
Well Being Gifts & Value Sets     93 469.28  374.40
Digestive Care                    92 681.93  244.50
Protein                           89 951.53  790.00
Beauty Supplements Value Sets     87 514.75  290.00
Immunity                          85 702.20  479.00
Appetite Suppressant              85 414.50  269.00
Sexual Health Vitamins            85 428.82  350.00
Whitening                         84 318.95  197.00
Stress, Sleep, and Anxiety        82 497.93  337.50
Slimming Beverages                82 329.15  240.00
Nutritional Foods & Drinks        82 687.46  602.50
Multivitamins                     82 318.39  185.00
Heart & Blood Pressure            82 536.97  358.50
Acne Care                         82 488.73  290.00
Herbs & Traditional Medicine      82 134.75   77.50
Mass Gainer                       82 832.90  640.00
Weight Management Value Sets      82 628.79  344.50
Women's Health                    82 462.18  285.00
Men's Health                      81 518.93  330.00
Brain & Memory                    81 417.89  249.00
Breast Enlargement                80 206.97  129.00
Meal Replacement                  80 871.25  739.00
Hair & Nail                       79 467.60  309.00
Food Supplement                   32 355.09  234.50

In [74]:
df

,Id,Section,Name,Price,Total Sold,Total Reviews,Shop Location
0,4799179886,Acne Care,DHC Vitamin B-Mix วิตามินบีรวม (สำหรับ 20 วัน),75.00,0,0,Pathum Thani
1,4795171651,Acne Care,ซิงค์ Vistra Zinc วิสทร้า ซิงค์ 15 มก. ขนาด 20...,79.00,0,0,Chiang Mai
2,4790242641,Acne Care,Blackmores แบลคมอร์ส Bio Zinc A Chelate (90 T...,224.00,0,0,Surin
3,4789940606,Acne Care,1แถม1 กลูต้าวิตมี กลูต้าส้มเลือด Gluta With Me...,290.00,0,0,Udon Thani
4,4787161067,Acne Care,🎌 DHC Vitamin B-Mix Persistent วิตามินบีรวม แบ...,149.00,0,0,Bangkok
...,...,...,...,...,...,...,...
67517,4806492324,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,220.00,50,0,Bangkok
67518,4806483337,Food Supplement,โคลีนบี วิตามินบีรวม วิตามินบี Choline - B G...,280.00,69,0,Bangkok
67532,4808549166,Food Supplement,Goodies โปรตีนพืชรสช็อคโกแลต 1 กระปุก,"1,390.00",0,3,Nakhon Pathom
67553,4808500844,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,560.00,48,0,Pathum Thani
67557,4806492324,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,560.00,50,0,Bangkok

In [75]:
df['Revenue'] = df['Total Sold'] * df['Price']

In [76]:
df['Review Rate'] = df['Total Reviews'] / (df['Total Sold'] + 1)

In [77]:
section_analysis = df.groupby('Section').agg(Product_count=('Price', 'count'),
                                             Avg_price=('Price','mean'),
                                             Avg_sold=('Total Sold','mean'),
                                             Avg_reviews=('Total Reviews','mean'),
                                             Total_Revenue=('Revenue','sum'),
                                             Avg_Review_rate=('Review Rate','mean')).round(2).sort_values('Total_Revenue',ascending=False)
section_analysis

,Product_count,Avg_price,Avg_sold,Avg_reviews,Total_Revenue,Avg_Review_rate
Section,,,,,,
Skin Nourishment,137,301.17,"1,152.68",271.62,"36,645,892.76",0.18
Protein,89,951.53,900.75,739.13,"27,753,968.00",4.34
Slimming Beverages,82,329.15,"1,446.30",302.73,"22,101,593.00",0.29
Mass Gainer,82,832.90,605.18,151.84,"19,687,419.00",0.13
Pregnancy Care,128,662.84,317.64,60.91,"19,557,782.00",0.10
Nutritional Foods & Drinks,82,687.46,371.61,63.72,"16,382,341.00",0.18
Men's Health,81,518.93,576.21,137.94,"16,368,676.00",0.17
Fat Blockers & Burners,98,516.55,"1,287.50",330.98,"13,901,181.48",1.36
Bone & Joint Support,94,591.33,699.80,156.29,"13,797,982.14",0.37
Immunity,85,702.20,654.28,188.87,"13,670,285.00",0.25
Appetite Suppressant,85,414.50,"1,083.49",214.86,"13,523,945.28",0.20
Pre-Workout,100,716.75,229.80,28.05,"13,489,313.00",0.08
Brain & Memory,81,417.89,700.62,128.38,"11,278,417.00",0.26
Detoxification,112,501.95,507.21,116.29,"11,034,659.00",0.15
Whitening,84,318.95,696.57,252.42,"10,854,443.00",1.44
"Stress, Sleep, and Anxiety",82,497.93,371.59,69.30,"10,563,084.00",0.21
Hair & Nail,79,467.60,382.70,85.28,"8,932,262.90",0.37
Sexual Health Vitamins,85,428.82,356.75,114.21,"7,630,313.00",0.38
Well Being Gifts & Value Sets,93,469.28,186.86,35.97,"7,480,400.00",0.26
Women's Health,82,462.18,459.62,99.21,"7,389,053.00",0.11
Beauty Supplements Value Sets,87,514.75,376.98,71.34,"7,017,485.72",0.19
Multivitamins,82,318.39,401.63,242.94,"6,185,966.80",1.32
Digestive Care,92,681.93,454.58,156.22,"5,254,851.30",0.23
Food Supplement,32,355.09,980.22,383.06,"5,089,655.00",0.20
Herbs & Traditional Medicine,82,134.75,694.38,101.09,"5,039,821.50",0.13
Acne Care,82,488.73,277.29,48.40,"4,717,499.96",0.30
Weight Management Value Sets,82,628.79,391.54,80.78,"4,411,968.00",0.18
Heart & Blood Pressure,82,536.97,368.32,83.24,"4,308,075.28",0.23
Meal Replacement,80,871.25,275.92,45.25,"2,611,516.00",0.20
Breast Enlargement,80,206.97,439.59,51.71,"2,469,359.15",0.11

In [78]:
df.groupby('Shop Location').agg(Product_Count=('Price', 'count'),
    Avg_Price=('Price', 'mean'),
    Avg_Sold=('Total Sold', 'mean'),
    Total_Revenue=('Revenue', 'sum')).round(2).sort_values('Total_Revenue', ascending=False).head(15)

               Product_Count  Avg_Price  Avg_Sold  Total_Revenue
Shop Location
Bangkok                 1101     514.58    673.90 164,886,280.23
Pathum Thani             237     462.63    813.43  42,988,414.00
Nonthaburi               197     586.52  1,019.72  38,384,718.68
Khon Kaen                 50     453.44  1,722.20  23,884,589.00
Samut Prakan             167     673.21    266.45  17,398,584.64
Chiang Mai                89     709.46    161.70   5,735,177.00
Sakon Nakhon              15     328.93  2,765.13   5,364,643.00
Lopburi                   13     987.15    572.08   5,017,198.00
Saraburi                  36     262.85    569.44   4,940,408.96
Surat Thani               11     676.00  1,101.09   3,354,680.00
Chachoengsao              20     540.45    593.95   3,174,263.56
Pattani                   10     147.50  2,803.90   2,579,200.00
Buri Ram                   6     520.67    607.00   2,516,341.00
Udon Thani                25     301.52  1,175.08   2,423,664.00
Chai Nat                   5     411.80  1,970.20   2,419,364.00

In [79]:
df['Price'].describe()
df['Price'].value_counts(bins=5).sort_index()

(3.408, 1127.2]     2341
(1127.2, 2245.4]     217
(2245.4, 3363.6]      35
(3363.6, 4481.8]      23
(4481.8, 5600.0]       6
Name: count, dtype: int64

In [80]:
df.nlargest(10,'Revenue')[['Name', 'Section', 'Price', 'Total Sold', 'Total Reviews', 'Revenue']]

,Name,Section,Price,Total Sold,Total Reviews,Revenue
49665,turbo max two up TWO UP by Turbomax ทูอัพ บาย ...,Men's Health,845.00,9541,1633,"8,062,145.00"
64891,Optimum Nutrition Creatine เพิ่มกล้ามเนื้อ เพิ...,Pre-Workout,"1,100.00",4267,522,"4,693,700.00"
42967,บูสท์ ออปติมัม Whey Protein,Immunity,795.00,5849,1027,"4,649,955.00"
40088,MATELL Plant-Based Protein Isolate แพลนต์เบสด์...,Protein,449.00,9999,6282,"4,489,551.00"
64166,MATELL Mass Whey Protein Gainer 2 lb แมส เวย์ ...,Mass Gainer,449.00,9999,2258,"4,489,551.00"
30313,Ensure Gold เอนชัวร์ โกลด์ อาหารเสริมสูตรครบถั...,Nutritional Foods & Drinks,808.00,4635,857,"3,745,080.00"
30153,Ensure Gold เอนชัวร์ โกลด์ อาหารเสริมสูตรครบถั...,Nutritional Foods & Drinks,805.00,4635,857,"3,731,175.00"
6741,Lemona Collagen เลโมนา คอลลาเจน / Lemona Gyeol...,Skin Nourishment,369.00,9999,2092,"3,689,631.00"
7782,Lemona Collagen เลโมนา คอลลาเจน / Lemona Gyeol...,Skin Nourishment,369.00,9999,2095,"3,689,631.00"
48861,((ของแท้ มี QR code)) Nature King Royal Jelly ...,"Stress, Sleep, and Anxiety",386.00,8128,1569,"3,137,408.00"

In [81]:
df.dtypes

Id                 int64
Section           object
Name              object
Price            float64
Total Sold         int64
Total Reviews      int64
Shop Location     object
Revenue          float64
Review Rate      float64
dtype: object

In [82]:
#df['Price Segment'] = pd.cut(df['Price'],
                             #bins=[0,200,500,1000,6000],
                             #labels=['Budget', 'Mid-Range', 'Premium', 'Luxury'])
condition = [df['Price'] <= 200,
    df['Price'] <= 500,
    df['Price'] <= 1000,
    df['Price'] > 1000]
choices = ['Budget', 'Mid-Range', 'Premium', 'Luxury']
df['Price Segment'] = np.select(condition,choices,default='')

df.groupby('Price Segment').agg(
    Count=('Price', 'count'),
    Avg_Sold=('Total Sold', 'mean'),
    Avg_Reviews=('Total Reviews', 'mean'),
    Total_Revenue=('Revenue', 'sum')
).round(2)

               Count  Avg_Sold  Avg_Reviews  Total_Revenue
Price Segment
Budget           912  1,101.59       268.76 125,130,427.29
Luxury           314     49.60         8.54  21,503,631.64
Mid-Range        871    480.83       168.50 125,577,125.04
Premium          525    198.18        35.46  76,938,025.30

In [83]:
df[['Price', 'Total Sold', 'Total Reviews', 'Revenue']].corr().round(2)

               Price  Total Sold  Total Reviews  Revenue
Price           1.00       -0.16          -0.09    -0.05
Total Sold     -0.16        1.00           0.54     0.76
Total Reviews  -0.09        0.54           1.00     0.41
Revenue        -0.05        0.76           0.41     1.00

In [84]:
df['Location Type'] = df['Shop Location'].apply(lambda x:'Bangkok' if x == 'Bangkok' else 'Rural')

df.groupby('Location Type').agg(Count=('Price','count'),
                                Avg_price=('Price','mean'),
                                Avg_sold=('Total Sold', 'mean'),
                                Avg_reviews=('Total Reviews', 'mean'),
                                Total_Revenue=('Revenue','sum')).round(2)

               Count  Avg_price  Avg_sold  Avg_reviews  Total_Revenue
Location Type
Bangkok         1101     514.58    673.90       157.76 164,886,280.23
Rural           1521     526.84    526.69       157.45 184,262,929.04

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2622 entries, 0 to 67557
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             2622 non-null   int64
 1   Section        2622 non-null   object
 2   Name           2622 non-null   object
 3   Price          2622 non-null   float64
 4   Total Sold     2622 non-null   int64
 5   Total Reviews  2622 non-null   int64
 6   Shop Location  2622 non-null   object
 7   Revenue        2622 non-null   float64
 8   Review Rate    2622 non-null   float64
 9   Price Segment  2622 non-null   object
 10  Location Type  2622 non-null   object
dtypes: float64(3), int64(3), object(5)
memory usage: 245.8+ KB

________________________________________________________________________________________________________________________________________________________

# 🤖 Section 4: Machine Learning

In [86]:
df

,Id,Section,Name,Price,Total Sold,Total Reviews,Shop Location,Revenue,Review Rate,Price Segment,Location Type
0,4799179886,Acne Care,DHC Vitamin B-Mix วิตามินบีรวม (สำหรับ 20 วัน),75.00,0,0,Pathum Thani,0.00,0.00,Budget,Rural
1,4795171651,Acne Care,ซิงค์ Vistra Zinc วิสทร้า ซิงค์ 15 มก. ขนาด 20...,79.00,0,0,Chiang Mai,0.00,0.00,Budget,Rural
2,4790242641,Acne Care,Blackmores แบลคมอร์ส Bio Zinc A Chelate (90 T...,224.00,0,0,Surin,0.00,0.00,Mid-Range,Rural
3,4789940606,Acne Care,1แถม1 กลูต้าวิตมี กลูต้าส้มเลือด Gluta With Me...,290.00,0,0,Udon Thani,0.00,0.00,Mid-Range,Rural
4,4787161067,Acne Care,🎌 DHC Vitamin B-Mix Persistent วิตามินบีรวม แบ...,149.00,0,0,Bangkok,0.00,0.00,Budget,Bangkok
...,...,...,...,...,...,...,...,...,...,...,...
67517,4806492324,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,220.00,50,0,Bangkok,"11,000.00",0.00,Mid-Range,Bangkok
67518,4806483337,Food Supplement,โคลีนบี วิตามินบีรวม วิตามินบี Choline - B G...,280.00,69,0,Bangkok,"19,320.00",0.00,Mid-Range,Bangkok
67532,4808549166,Food Supplement,Goodies โปรตีนพืชรสช็อคโกแลต 1 กระปุก,"1,390.00",0,3,Nakhon Pathom,0.00,3.00,Luxury,Rural
67553,4808500844,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,560.00,48,0,Pathum Thani,"26,880.00",0.00,Premium,Rural
67557,4806492324,Food Supplement,โคซานอล โคซานอล มัลติ แพลนท์ โอเมก้า 3 ออยล์ น...,560.00,50,0,Bangkok,"28,000.00",0.00,Premium,Bangkok

In [87]:
x = df[['Total Sold', 'Total Reviews', 'Review Rate', 'Section', 'Location Type']].copy()
y = df['Price']

x = pd.get_dummies(x,columns=['Section', 'Location Type'])
x

,Total Sold,Total Reviews,Review Rate,Section_Acne Care,Section_Appetite Suppressant,Section_Beauty Supplements Value Sets,Section_Bone & Joint Support,Section_Brain & Memory,Section_Breast Enlargement,Section_Detoxification,...,Section_Sexual Health Vitamins,Section_Skin Nourishment,Section_Slimming Beverages,"Section_Stress, Sleep, and Anxiety",Section_Weight Management Value Sets,Section_Well Being Gifts & Value Sets,Section_Whitening,Section_Women's Health,Location Type_Bangkok,Location Type_Rural
0,0,0,0.00,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,0,0,0.00,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,0,0,0.00,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,0,0,0.00,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,0,0,0.00,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67517,50,0,0.00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
67518,69,0,0.00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
67532,0,3,3.00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
67553,48,0,0.00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
67557,50,0,0.00,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [88]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [89]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2097, 35)
(525, 35)
(2097,)
(525,)

In [90]:
from sklearn.linear_model import LinearRegression
from sklearn import set_config
set_config(display='text')
lm = LinearRegression()
lm.fit(X_train,y_train)
lm.score(X_train,y_train)

0.10536523471545323

In [91]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(X_train,y_train)

RandomForestRegressor()

In [92]:
print('Linear Regression R²:', lm.score(X_test, y_test))
print('Random Forest R²:', rf.score(X_test, y_test))

Linear Regression R²: 0.1347838573624981
Random Forest R²: 0.1449097767828288

In [93]:
df.columns

Index(['Id', 'Section', 'Name', 'Price', 'Total Sold', 'Total Reviews',
       'Shop Location', 'Revenue', 'Review Rate', 'Price Segment',
       'Location Type'],
      dtype='object')

In [101]:
x = df[['Price', 'Total Reviews', 'Review Rate', 'Section', 'Location Type']].copy()
y = df['Total Sold']

x = pd.get_dummies(x, columns=['Section', 'Location Type'])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

lm2 = LinearRegression()
lm2.fit(X_train,y_train)

rf2 = RandomForestRegressor()
rf2.fit(X_train,y_train)

print('Linear R²:', lm2.score(X_test, y_test))
print('Random Forest R²:', rf2.score(X_test, y_test))

Linear R²: 0.7203176903570486
Random Forest R²: 0.9784934432178279

In [104]:
importance = pd.DataFrame({'Feature' : X_train.columns ,
                           'Importance' : rf2.feature_importances_}).sort_values('Importance',ascending=False)
importance.head(10)

                               Feature  Importance
1                        Total Reviews        0.94
2                          Review Rate        0.05
0                                Price        0.00
13                 Section_Hair & Nail        0.00
24                     Section_Protein        0.00
11      Section_Fat Blockers & Burners        0.00
23              Section_Pregnancy Care        0.00
28  Section_Stress, Sleep, and Anxiety        0.00
33               Location Type_Bangkok        0.00
26            Section_Skin Nourishment        0.00

In [107]:
x2 = df[['Price', 'Review Rate', 'Section', 'Location Type']].copy()
y2 = df['Total Sold']

x2 = pd.get_dummies(x2, columns=['Section', 'Location Type'])

X_train2, X_test2, y_train2, y_test2 = train_test_split(x2, y2, test_size=0.2, random_state=42)

rf3 = RandomForestRegressor(n_estimators=100, random_state=42)
rf3.fit(X_train2, y_train2)

print('Random Forest R² (no leakage):', rf3.score(X_test2, y_test2))

Random Forest R² (no leakage): 0.3717562215744654

In [108]:
importance2 = pd.DataFrame({
    'Feature': X_train2.columns,
    'Importance': rf3.feature_importances_
}).sort_values('Importance', ascending=False)

importance2.head(10)

                           Feature  Importance
1                      Review Rate        0.44
0                            Price        0.31
33             Location Type_Rural        0.02
32           Location Type_Bangkok        0.02
26      Section_Slimming Beverages        0.02
5     Section_Bone & Joint Support        0.02
10  Section_Fat Blockers & Burners        0.01
25        Section_Skin Nourishment        0.01
3     Section_Appetite Suppressant        0.01
23                 Section_Protein        0.01

________________________________________________________________________________________________________________________________________________________

# Export CSV

In [95]:
df.to_csv("health_wellness_cleaned.csv",index=False)